# -*- coding: utf-8 -*-
"""Module4medium.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1of_MuSpAeDON3PeKmAGOgtLIUlZlaS0T
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import json

with open("imdb_movies_2000to2022.prolific (1).json", "r") as f:
    data = [json.loads(line) for line in f]
df = pd.DataFrame(data)
df['main_genre'] = df['genres'].apply(lambda g: g[0] if isinstance(g, list) and len(g) > 0 else 'Unknown')
df['avg_rating'] = df['rating'].apply(lambda r: r.get('avg') if isinstance(r, dict) else None)
df = df[['main_genre', 'avg_rating']].dropna()
df = df.sample(n=1000, random_state=42)  # keep it simple
df_encoded = pd.get_dummies(df, columns=['main_genre'])
scaler = StandardScaler()
df_encoded['avg_rating'] = scaler.fit_transform(df_encoded[['avg_rating']])

wcss = []
K_range = range(2, 20)
for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(df_encoded)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(10, 6))
plt.plot(K_range, wcss, marker='o')
plt.title('Elbow Method for Choosing k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Within-Cluster Sum of Squares')
plt.grid(True)
plt.show()
plt.savefig("Elbow.png")

import pandas as pd


df = pd.DataFrame({
    'Movie Title': ['Frozen', 'Titanic', 'Get Out'],
    'main_genre': ['Animation', 'Romance', 'Horror']
})


encoded_df = pd.get_dummies(df, columns=['main_genre'])


print(encoded_df)